const { User, Booking, Payment, CorporateCustomer, Employee, Account } = require('../models');

// Get admin dashboard statistics
const getAdminDashboard = async (req, res) => {
  try {
    // Get total counts
    const totalUsers = await User.count();
    const totalBookings = await Booking.count();
    const totalPayments = await Payment.count();
    
    // Get counts by status
    const pendingBookings = await Booking.count({ where: { bk_status: 'PENDING' } });
    const confirmedBookings = await Booking.count({ where: { bk_status: 'CONFIRMED' } });
    const cancelledBookings = await Booking.count({ where: { bk_status: 'CANCELLED' } });
    
    // Get financial summary from Account model
    const accounts = await Account.findAll({
      attributes: ['ac_totamt', 'ac_rcvdamt', 'ac_pendamt']
    });
    
    let totalRevenue = 0;
    let totalPending = 0;
    let totalAmount = 0;
    
    accounts.forEach(account => {
      totalRevenue += parseFloat(account.ac_rcvdamt) || 0;
      totalPending += parseFloat(account.ac_pendamt) || 0;
      totalAmount += parseFloat(account.ac_totamt) || 0;
    });
    
    // Get employee performance
    const employees = await User.findAll({ 
      where: { us_usertype: 'employee' },
      attributes: ['us_usid', 'us_fname', 'us_lname'],
      include: [{
        model: Employee,
        attributes: ['em_dept'],
        required: false
      }]
    });
    
    const employeeStats = [];
    
    for (const employee of employees) {
      const bookingCount = await Booking.count({ 
        where: { bk_agent: employee.us_usid } 
      });
      
      const confirmedCount = await Booking.count({ 
        where: { 
          bk_agent: employee.us_usid, 
          bk_status: 'CONFIRMED' 
        }
      });
      
      // Get total revenue generated by this employee through associated accounts
      const employeeBookings = await Booking.findAll({
        where: { bk_agent: employee.us_usid },
        include: [{
          model: Account,
          required: false
        }]
      });
      
      let revenue = 0;
      employeeBookings.forEach(booking => {
        if (booking.account) {
          revenue += parseFloat(booking.account.ac_rcvdamt) || 0;
        }
      });
      
      // Use emEmployee as the association name
      employeeStats.push({
        id: employee.us_usid,
        name: `${employee.us_fname} ${employee.us_lname || ''}`,
        department: employee.emEmployee ? employee.emEmployee.em_dept : '',
        totalBookings: bookingCount,
        confirmedBookings: confirmedCount,
        revenueGenerated: revenue
      });
    }
    
    // Get corporate customer summary
    const corporateCustomers = await CorporateCustomer.findAll({
      attributes: ['cu_company', 'cu_creditlmt', 'cu_creditused']
    });
    
    const corporateStats = corporateCustomers.map(customer => ({
      companyName: customer.cu_company,
      creditLimit: parseFloat(customer.cu_creditlmt) || 0,
      creditUsed: parseFloat(customer.cu_creditused) || 0,
      creditAvailable: (parseFloat(customer.cu_creditlmt) || 0) - (parseFloat(customer.cu_creditused) || 0)
    }));
    
    res.json({
      overview: {
        totalUsers,
        totalBookings,
        totalPayments,
        totalRevenue,
        totalPending,
        totalAmount
      },
      bookingStats: {
        pending: pendingBookings,
        confirmed: confirmedBookings,
        cancelled: cancelledBookings
      },
      employeePerformance: employeeStats,
      corporateCustomers: corporateStats
    });
  } catch (error) {
    console.error('Admin dashboard error:', error);
    res.status(500).json({ message: error.message });
  }
};

// Get employee dashboard statistics
const getEmployeeDashboard = async (req, res) => {
  try {
    const userId = req.user.us_usid;
    
    // Get employee info including department
    const employeeInfo = await User.findByPk(userId, {
      attributes: ['us_usid', 'us_fname', 'us_lname'],
      include: [{
        model: Employee,
        attributes: ['em_dept'],
        required: false
      }]
    });
    
    // Get employee's bookings
    const totalBookings = await Booking.count({ where: { bk_agent: userId } });
    const pendingBookings = await Booking.count({ 
      where: { 
        bk_agent: userId, 
        bk_status: 'PENDING' 
      }
    });
    const confirmedBookings = await Booking.count({ 
      where: { 
        bk_agent: userId, 
        bk_status: 'CONFIRMED' 
      }
    });
    
    // Get financial summary for employee through associated accounts
    const employeeBookings = await Booking.findAll({
      where: { bk_agent: userId },
      include: [{
        model: Account,
        required: false
      }]
    });
    
    let revenue = 0;
    employeeBookings.forEach(booking => {
      if (booking.account) {
        revenue += parseFloat(booking.account.ac_rcvdamt) || 0;
      }
    });
    
    // Use emEmployee as the association name
    res.json({
      employee: {
        name: `${employeeInfo.us_fname} ${employeeInfo.us_lname || ''}`,
        department: employeeInfo.emEmployee ? employeeInfo.emEmployee.em_dept : ''
      },
      overview: {
        totalBookings,
        pendingBookings,
        confirmedBookings,
        revenueGenerated: revenue
      }
    });
  } catch (error) {
    console.error('Employee dashboard error:', error);
    res.status(500).json({ message: error.message });
  }
};

// Get customer dashboard statistics
const getCustomerDashboard = async (req, res) => {
  try {
    const userId = req.user.us_usid;
    
    // Get customer's bookings
    const totalBookings = await Booking.count({ where: { bk_usid: userId } });
    const pendingBookings = await Booking.count({ 
      where: { 
        bk_usid: userId, 
        bk_status: 'PENDING' 
      }
    });
    const confirmedBookings = await Booking.count({ 
      where: { 
        bk_usid: userId, 
        bk_status: 'CONFIRMED' 
      }
    });
    
    // Get payment summary from associated accounts
    const customerBookings = await Booking.findAll({
      where: { bk_usid: userId },
      include: [{
        model: Account,
        required: false
      }]
    });
    
    let totalPaid = 0;
    let totalAmount = 0;
    let totalPending = 0;
    
    customerBookings.forEach(booking => {
      if (booking.account) {
        const received = parseFloat(booking.account.ac_rcvdamt) || 0;
        const total = parseFloat(booking.account.ac_totamt) || 0;
        const pending = parseFloat(booking.account.ac_pendamt) || 0;
        totalPaid += received;
        totalAmount += total;
        totalPending += pending;
      }
    });
    
    // Check if customer is corporate
    const corporateInfo = await CorporateCustomer.findOne({
      where: { cu_usid: userId },
      attributes: ['cu_company', 'cu_creditlmt', 'cu_creditused']
    });
    
    res.json({
      overview: {
        totalBookings,
        pendingBookings,
        confirmedBookings,
        totalPaid,
        totalAmount,
        totalPending
      },
      corporateInfo: corporateInfo ? {
        companyName: corporateInfo.cu_company,
        creditLimit: parseFloat(corporateInfo.cu_creditlmt) || 0,
        creditUsed: parseFloat(corporateInfo.cu_creditused) || 0
      } : null
    });
  } catch (error) {
    console.error('Customer dashboard error:', error);
    res.status(500).json({ message: error.message });
  }
};

module.exports = {
  getAdminDashboard,
  getEmployeeDashboard,
  getCustomerDashboard
};